[package]
name = "scale-codec-pvm"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "scale-codec-pvm"
path = "src/lib.rs"

[dependencies]
polkavm-derive = "0.25.0"

[dependencies.uapi]
package = "pallet-revive-uapi"
git = "https://github.com/paritytech/polkadot-sdk.git"
rev = "187cddde3799b5761c8036aaf137b93ba09fa526"
default-features = false
features = ["unstable-hostfn"]

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
